### ISSUE TITLE
License key leaked in REAPER folder

### ISSUE THREAD

**Issue by restorerootfs** [johnnovak/configs#1]
You have a Reaper license key in the Reaper folder. This is a security risk as anyone who knows where to find it can find a VALID license key to use with Reaper, leading to piracy.

**Comment by johnnovak** [comment]
Thanks. Did not think of this. Although largely a theoretical issue as you can use REAPER indefinitely anyway in shareware mode 😄 (I've done so for many years before finally buying a license, and I assume most people do the same)

**Comment by restorerootfs** [comment]
I guess REAPER is the WinRAR of the music world, huh?

**Comment by johnnovak** [comment]
> I guess REAPER is the WinRAR of the music world, huh?

Kinda :) Have removed the key.

**Comment by restorerootfs** [comment]
Alright, in that case I'll close the thread.
